version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8080:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: sqlilab
            MYSQL_ROOT_PASSWORD: root 
        volumes:
              - ./db/sqlilab.sql:/docker-entrypoint-initdb.d/sqlilab.sql
        networks:
            - default